export enum NotificationType {
  NOUVELLE_OFFRE = 'NOUVELLE_OFFRE',
  CANDIDATURE_RECUE = 'CANDIDATURE_RECUE',
  CANDIDATURE_ACCEPTEE = 'CANDIDATURE_ACCEPTEE',
  CANDIDATURE_REFUSEE = 'CANDIDATURE_REFUSEE',
  RAPPEL = 'RAPPEL',
}
